### ISSUE TITLE
Feature request: nullable annotation on properties

### ISSUE THREAD

**Issue by espenrl** [PaulBraetz/RhoMicro.CodeAnalysis#37]
Given the following union type

``` csharp
[UnionType<TokenSuccessResponse>(Alias = "Success")]
[UnionType<TokenErrorResponse>(Alias = "Error")]
internal partial class TokenResponse;
```

The compiler doesn't recognize `IsSuccess` as a null check for `AsSuccess`.

<img width="313" alt="image" src="https://github.com/user-attachments/assets/c8e9d424-8d4a-4445-afa8-5f7f8f871ca1">

Annotating IsSuccess / IsError would be great.

``` csharp
[MemberNotNullWhen(false, nameof(AsError))]
[MemberNotNullWhen(true, nameof(AsSuccess))]
public bool IsSuccess { get; set; }

[MemberNotNullWhen(true, nameof(AsError))]
[MemberNotNullWhen(false, nameof(AsSuccess))]
public bool IsError { get; set; }
```

**Comment by SleepWellPupper** [comment]
Are `TokenSuccessResponse` and `TokenErrorResponse` reference types?

**Comment by espenrl** [comment]
Yes, they are both reference types defined as `internal sealed class`.

**Comment by SleepWellPupper** [comment]
Thanks for posting the issue, if you discover any problems in my implementation for your usecase, feel free to open a new issue or revive this one.
